# Generated by Django 2.2.11 on 2020-03-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ewkfbwebfhewbfjewbfhjewbfjehwfbjewf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhhh', models.BigIntegerField()),
            ],
        ),
    ]
